### ISSUE TITLE
[Suggestion] Prefix/Suffix availability 

### ISSUE THREAD

**Issue by Haroldyolo** [thirdy/durian#20]
Hi again Thirdy. Another suggestion from me.

Would it be possible if you can add another column, next to the displayed results showing the availability of an open Prefix or Suffix? Or... once the item is displayed showing how many Prefix/Suffix it have? 

Btw Thank a lot for the verify function it works amazing! And the new version of durian rocks!

Regards.

**Comment by thirdy** [comment]
Yep, will try to implement it like [Forgotten mods](https://www.pathofexile.com/forum/view-thread/1164052). If there's an open prefix/suffix, will label it as another affix, something like this:

```
<open suffix>
```

Then it would be cool to be able to click on it, and choose available master crafts. 

This will have to wait though, haven't played Talisman much., so. But it would be great if somebody makes a pull request to implement this.

Thanks for the suggestion

**Comment by Haroldyolo** [comment]
Let me know if I can help in any way. Over the holidays I am not at work and while I don't have any programming experience I don't mind getting data and inputting it somewhere etc. Let me know.

**Comment by thirdy** [comment]
Yep. There's a big effort needed build a map of poe.trade affixes against tiers and suffix/prefix.

I tried this today, but it's too much for me right now:

```
https://docs.google.com/spreadsheets/d/1TmP6fl_Sd4Lc0fIw4dWn-TeUT2_WQqQPGfDRZUjCvIg/edit#gid=1
```

Right now, that spreadsheet needs a column for the equivalent poe.trade affix which I've listed here:

```
https://github.com/thirdy/durian/blob/master/durian/terms/reference/explicitmods-all.txt
```

For example:

```
# Life Regenerated per second
```

is for row 515 to 520 (Base Life Regeneration Rate Per Second).

This way, in the code, I can translate "# Life Regenerated per second" to these rows and get the data needed.

This spreadsheet is taken from a another spreadsheet [by patirce on this post](https://www.pathofexile.com/forum/view-thread/54167/page/20#p11327452), but there's no requirement to use it. If it makes sense to start from scratch then so be it. What's important is to have a way to map the poe.trade affixes to the data required.

There's also data from poeaffix found here:

https://github.com/poeaffix/poeaffix.github.io/tree/master/templates

Then there poedb:

http://poedb.tw/us/mod.php?type=9

Then PyPoE as well (which I'll try):

https://www.reddit.com/r/pathofexiledev/comments/3w1ajt/anyone_already_written_an_algorithm_for/

Too bad I replied to late. but better late not never.

**Comment by thirdy** [comment]
Gonna implement this with javascript, working on it atm

**Comment by Haroldyolo** [comment]
Let me know if I can help in any way

**Comment by thirdy** [comment]
Yep, would be great if you can fill up the Mod column (column C):

https://docs.google.com/spreadsheets/d/1TmP6fl_Sd4Lc0fIw4dWn-TeUT2_WQqQPGfDRZUjCvIg/edit?usp=sharing

With values taken from poe.trade (which I've listed here):

https://github.com/thirdy/durian/blob/master/durian/terms/reference/explicitmods-all.txt

**Comment by thirdy** [comment]
implemented. except for hybrid mods which will have to be solved in another day.

Hybrid mods would have to be handled in the javascript code in a special way. Right now every mod is treated as individuals. But hybrid mods require logic that depends on 'sibling' mods.

The next step in solving this is to write down all the cases where hybrid mods can be solved. Then each of these cases, we should have a sample item to test it on.

If somebody can work that out, then it would be really awesome.
