### ISSUE TITLE
Crashing when i added crit multi to the expicitmods.txt

### ISSUE THREAD

**Issue by PastaAdventures** [thirdy/durian#24]
i got it to search for crit multi but i crashes about 10 sec after it completes 
Here the error log: 
[hs_err_pid76184.txt](https://github.com/thirdy/durian/files/75272/hs_err_pid76184.txt)

and heres what i added
gmulti                               =      mod_name=(pseudo) (total) #% increased Global Critical Strike 

Multiplier&mod_min=&mod_max=&group_type=And&group_min=&group_max=&group_count=1
(\d+)gmulti                          =      mod_name=(pseudo) (total) #% increased Global Critical Strike 

Multiplier&mod_min=$GROUP1&mod_max=&group_type=And&group_min=&group_max=&group_count=1
(\d+)-(\d+)gmulti                     =     mod_name=(pseudo) (total) #% increased Global Critical Strike 

Multiplier&mod_min=$GROUP1&mod_max=$GROUP2&group_type=And&group_min=&group_max=&group_count=1

**Comment by thirdy** [comment]
I saw a Socket Timeout., so it's mostly related to internet connection. Can you send me your "durian.log" as soon as this happens again, that would be really helpful.

The search term definition you added has extra newlines, try this:

```
gmulti                    =      mod_name=(pseudo) (total) #% increased Global Critical Strike Multiplier&mod_min=&mod_max=&group_type=And&group_min=&group_max=&group_count=1
(\d+)gmulti               =      mod_name=(pseudo) (total) #% increased Global Critical Strike Multiplier&mod_min=$GROUP1&mod_max=&group_type=And&group_min=&group_max=&group_count=1
(\d+)-(\d+)gmulti         =      mod_name=(pseudo) (total) #% increased Global Critical Strike Multiplier&mod_min=$GROUP1&mod_max=$GROUP2&group_type=And&group_min=&group_max=&group_count=1
```
