### ISSUE TITLE
4.1.10 download (standalone) zip file is corrupt

### ISSUE THREAD

**Issue by Wraeyth** [thirdy/durian#32]
4.1.10 download (standalone) zip file is corrupt

**Comment by kyri0** [comment]
I can't download it to test it right now, but thirdy will surelly do it when he sees it here. For now, you can  download one of the older versions (if you already don't have one) and copy the directory "jre1.8.0_66" and the "run.bat" file to the Durian 4.1.10 non-standalone folder (after you download and extract it).

**Comment by thirdy** [comment]
Re-uploading now

**Comment by thirdy** [comment]
Re-uploaded. @Wraeyth can you try again?

**Comment by Wraeyth** [comment]
When downloaded, I can extract via 7zip fine but double clicking to open in Windows continues to state that the file is invalid.

This is with version 5

**Comment by kyri0** [comment]
From which file are you trying to run the standalone version? You should open the 'run.bat' and not the 'durian.jar' file. Again, if this doesn't work, I ask you to refer to my first comment, as i've downloaded the 0.5 version here and it works fine.

**Comment by Wraeyth** [comment]
You are not understanding what I've said. The .zip itself is the issue. If I extract via 7zip, it is fine. If I attempt to open it via Windows instead, it says it is an invalid file.

In the end it is still usable but not everyone will know to try using a utility to extract when they are told it is invalid when they double click it.

**Comment by kyri0** [comment]
Sorry for not having understood you. You're right, as I was using 7zip, I had no problem extracting the files, and, as the title of the issue suggest, I thought you were having a problem only with the standalone version and not with both of them. The problem was already solved, though. You can download the 0.5.1 version and extract it with the Windows tool now.

**Comment by Wraeyth** [comment]
Awesome, great to hear. Not a huge issue for me, but for some it might be a big deal.

**Comment by thirdy** [comment]
Hi, this has been fixed in v0.5.1.

Cheers!
