### ISSUE TITLE
Blacklist for Sellers

### ISSUE THREAD

**Issue by marshauf** [thirdy/durian#43]
hi,

a blacklist for(against) sellers which removes found items from the search list.
Could be an independent list or the POE ignore list.

**Comment by thirdy** [comment]
Hi, if you check the Config tab, there's a way there to blacklist account names.

Have a look at this reddit comment:

https://www.reddit.com/r/pathofexile/comments/3z9ms6/durian_v05_mod_affix_tier_item_art_improved_sound/cykhto9

Let me know if it works for you.

**Comment by marshauf** [comment]
Ah, I am sorry. I didn't check the config file for it. I thought it would be in it's own tab.
Thank you.
