### ISSUE TITLE
high CPU usage

### ISSUE THREAD

**Issue by Dominik-O22** [thirdy/durian#46]
When ever durian has to display search results, the CPU usage jumps up to the point that it uses around 25% of my CPU performance

**Comment by thirdy** [comment]
yep high indeed. I might have code that shouldn't be in the code for displaying the search result table.

**Comment by Dominik-O22** [comment]
it is the art renderer which causes this, because the moment i turn of item art the cpu usage drops to acceptable

**Comment by thirdy** [comment]
i see. thanks for letting me know

**Comment by thirdy** [comment]
It's this line in ArtColumnRenderer.java:

`table.setRowHeight(row, image.getIconHeight());`

re-adjusting the row height is apparently expensive and i've placed it in the wrong place

**Comment by thirdy** [comment]
fixed now wit 0.6.0, let me know how it goes
