### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Dominik-O22** [thirdy/durian#55]
After leaving this program up over night i  noticed it took up over 2GB RAM

**Comment by thirdy** [comment]
have a look at:

https://www.reddit.com/r/pathofexile/comments/3z9ms6/durian_v05_mod_affix_tier_item_art_improved_sound/cykn9iw

let me know if that works

**Comment by Dominik-O22** [comment]
okay modified the batch file now, hopefully it works, but this should be added to the standard run.bat as i dont see a reason for durian to even have 2gb of ram, yes it will take up a bit more cpu time for gc, but i think most people will take that over 2gb of ram for durian

**Comment by Dominik-O22** [comment]
so after letting durian run for some while , i can say it decreases it a bit, but the even though it is supposed to be limited to 512mb it is now up to 900mb

**Comment by thirdy** [comment]
can you try to disable the graphics. i think I coded that poorly, it's
probably re-loading the graphics assets on a loop -- just a suspicion. will
investigate this as soon as i can

On Sun, Jan 31, 2016 at 5:21 AM, Dom notifications@github.com wrote:

> so after letting durian run for some while , i can say it decreases it a
> bit, but the even though it is supposed to be limited to 512mb it is now up
> to 900mb
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thirdy/durian/issues/55#issuecomment-177457192.

## 

## 

http://sites.google.com/site/thirdyderivera/

**Comment by Dominik-O22** [comment]
so after about 15h is durian now takes up 710kb of ram so disabling the art slows down the memory leak, but does not stop it

**Comment by thirdy** [comment]
did some changes that might help. can you try version 5.5. thanks!

**Comment by Dominik-O22** [comment]
so after letting it run for a bit it appears to be worse

**Comment by thirdy** [comment]
did some changes again with 0.6

**Comment by thirdy** [comment]
re-open if it's stilll a problem
