### ISSUE TITLE
No sortdps, no pdps + dps

### ISSUE THREAD

**Issue by ghost** [thirdy/durian#58]
can't sort by total DPS, works only for physical sortpdps
can't search for e.g. 1hsword 300pdps 400dps
can't search for flat accuracy e.g. 200acc? 200accuracy?

would be nice if there was a docu with all the commands listed

**Comment by Dominik-O22** [comment]
just add this line 

```
sortdps                                 =       dps
```

to the sorts.txt file
and it will sort by dps
created a pull request of this change, so after thirdy merges that it should be in the next release as well
and flat acc is also added

**Comment by kyri0** [comment]
"can't search for e.g. 1hsword 300pdps 400dps"
I can search for 300pdps and 400dps, if you didn't find any results, it was probably because there were none.
