### ISSUE TITLE
Highlight Corrupt Status

### ISSUE THREAD

**Issue by Dominik-O22** [thirdy/durian#66]
I think marking the corrupted status in red if corrupted, would make it easier to see if an item is corrupted, because as it sands right now it is rather hard to tell if that is the case at a glance

**Comment by thirdy** [comment]
agreed

**Comment by thirdy** [comment]
Added a text flair in uppercase instead:

[img](https://cloud.githubusercontent.com/assets/75921/13200189/c3bf4e78-d878-11e5-859e-911028edfbe5.PNG)

closing ticket. the coloring red is possible but I decided that adding the text is good enough and bec it's a lot easier to implement.
