### ISSUE TITLE
option to not search for (pseudo)

### ISSUE THREAD

**Issue by Turmfalke2** [thirdy/durian#68]
hi,
It would be nice to have an option to not search for (pseudo) mods. A jewel with 10 spell power is not the same as a jewel with 10 fire damage. Not all skills that are affected by increased fire damage are also affected by spell power.

**Comment by Dominik-O22** [comment]
Given how this program works, this would only be possible by adding the non pseudo version under a new term, so to have a somewhat logical naming pattern, and the only group of skills that i can think of, that are not affected by spelldmg, are attack skills do you now of any other group of skills for which the pseudo is useless?

**Comment by Turmfalke2** [comment]
I am using detonated dead. Spell power does nothing for it, but increased fire damage is nice.

**Comment by Dominik-O22** [comment]
So if i didn't  misunderstood something you are looking for the modifier `#% increased Fire Damage`  which is already in the terms files 

```
firedmg|fdmg                        =       mod_name=#% increased Fire Damage&mod_min=&mod_max=&$MG
(\d+)(firedmg|fdmg)                 =       mod_name=#% increased Fire Damage&mod_min=$GROUP1&mod_max=&$MG
(\d+)-(\d+)(firedmg|fdmg)           =       mod_name=#% increased Fire Damage&mod_min=$GROUP1&mod_max=$GROUP2&$MG
```

it is the third group in mod-ofs.txt

**Comment by Turmfalke2** [comment]
The issue is if I am searching for "jewel 7mlife fsdmg" durian lists jewels with 7 increased life and 11% spell power. It then claims that 11% spellpower is the same as having 11% increased fire damage, which is not the case for detonated dead.

**Comment by Dominik-O22** [comment]
It returns that because you are looking for it fsdmg is shorthand for fire spell damage which only exists as a pseudo. If you want to look for increased fire damage use the correct term and not a term meaning something else and expecting it to be able to read your mind

**Comment by Turmfalke2** [comment]
Oh ok.. my bad
