### ISSUE TITLE
Display affix tier range

### ISSUE THREAD

**Issue by Ramses-II** [thirdy/durian#72]
Hey, 
I love Durian but I have an idea to improve the search. Right now affixes are shown for example as:

> [prefix][T7] 50.0 + # to maximum Life 

For many very experienced players it is easy to know that  chest can have up to XXX max life but not for everyone. The tiers are shown, but personally I do not know what is the max tier on that item. 
My suggestion:

> [prefix][T7/T9] 50.0 + # to maximum Life 
> or
> [prefix][T7/9] 50.0 + # to maximum Life 

I have absolutly no idea, but I think that this is not too hard to implement.

Further additions could be a search function for items with # tiers not lower than max tier -2. If it is unclear what is meant, give me a shout!
Greetings Ramses

**Comment by thirdy** [comment]
This can definitely be implemented at runtime; which means that this can be implemented just by going to the script tab and make changes there.

The whole logic for determining the final text for the modifier is done via the Script tab. There you'll see javascript.

In fm.js, lines 39 to 45 are the ff:

```
            //logger.info('affix found:' + affix.mod + ' tier: ' + affix.tier)
            affixLabel = affix.affix == 'Prefix' ? '[prefix]' : '[suffix]'
            tierLabel = '[T' + affix.tier + ']'
            valueLabel = mod.value
            modNameLabel = mod.name
            if(modNameLabel.startsWith('#')) modNameLabel = modNameLabel.substring(1)
            mod.forgottenMod = affixLabel + tierLabel + ' ' + valueLabel + ' ' + modNameLabel
```

Will have to write the code to grab the max possible tier from the affixes map (as defined in affixes.js).

Somebody who writes javascript will definitely know how; would be great if somebody can make it and make a pull request.

But in case; will implement it as soon as I can.

**Comment by Dominik-O22** [comment]
@thirdy you can close this issue now, as it is part of durian now
